<?
include("../include/init.php");
$title = "AscensionTek - Green Steel Homes Business Plan - Sustainable Homes";
$menuItem = "Business Plan";
include("../tpl/templateTop.php");
?>

<h1 align="center"><img src="../images/GreenSteelHomes.png" alt="Green Steel Homes" width="300" height="126"></h1>

<h1>Sustainable Homes </h1>
<p>&nbsp;</p>
<h2>Business Concept</h2>
<p>GSH is a home building company for the 21st century,
	with a range of innovations that distinguish it from
	the many other players in the market:</p>
<ul>
	<li>Extensive use of software and the internet in
				all aspects of the company to streamline
		operations.</li>
	<li>Fully sustainable homes incorporating environmentally-friendly
				 materials, design practices
		and technology.</li>
	<li> Smart housing concepts such as built-in internet
				and wireless networking.</li>
</ul>
<p>&nbsp;</p>
<p>Our homes will also offer the following important
	advantages:</p>
<ul>
	<li>Customers design their own floor plans using an
		online computer program.</li>
	<li>Price comparable with a project or off-the-plan
		home.</li>
	<li>Fast construction.</li>
	<li>Virtually free electricity and water during the
		life of the home. </li>
</ul>
<p>&nbsp;</p>
<h2>Design Features </h2>
<p> A Green Steel Home is a few great homes rolled
	into one.&nbsp; Features include:</p>
<ul>
	<li>Strong, steel frame (see <a href="<?php echo $smUrl; ?>/articles/WhySteel.php">Why
			Steel?</a>)</li>
	<li>Long-lasting; storm, earthquake, fire and termite
		resistant. </li>
	<li>Spacious, comfortable and stylish.</li>
	<li>Built using environmentally-friendly building
		materials. </li>
	<li>Thermally efficient, designed to use passive heating
		and cooling.</li>
	<li>Incorporating energy production technology such
		as solar panels and wind turbines.</li>
	<li>Water tanks and water recycling system.</li>
	<li>Energy-efficient hot water and cold water systems.</li>
	<li>Energy and water-efficient appliances and fixtures.</li>
	<li>A built-in wireless router and access point, providing
		internet all the time, anywhere in the house.</li>
	<li>Integrated with the natural environment through
		outdoor spaces, and permaculture and native
		plant gardens.</li>
</ul>
<p>&nbsp;</p>
<h2>Advanced Information Systems</h2>
<h3>Online design</h3>
<p>Most new residences are one of two varieties.&nbsp; The
	cheaper option is usually purchased off-the-plan
	or from a newly constructed estate or apartment complex,
	which means there will be many other residences
	with the same &quot;average family&quot; design.&nbsp; The
	more expensive option is an architecturally designed
	home.</p>
<p>However, most people cannot afford an architect,
	and therefore must settle for a house which has
	probably been designed for a family different from
	theirs.</p>
<p>What we do is provide a happy compromise.&nbsp; <strong>Users
		will be able to come to our website and design their
		own home online.</strong>&nbsp; The software will
		be able to produce accurate quotes and 3d views in
		real time (I have written programs to do this before
		- please refer to the <a href="ManagementTeam.php">Management
		Team</a> page for more information).</p>
<p>Our customers will receive the best of both worlds
	- a house they have designed themselves, for their
	own unique needs, yet without incurring the expense
	of an architect, building designer or engineer.</p>
<p>Another way that customers will be able to save
	money is to build their homes themselves.&nbsp; The
	homes will be available in kit form, complete with
	customised assembly instructions generated by our
	software.&nbsp; We will help owner/builders get the
	necessary licence through co-operation with training
	providers. </p>
<p>&nbsp;</p>
<h3>Automated integration with back office, warehouse,
	workshop, suppliers and builders.</h3>
<p>Once a customer has purchased a home online, the
	software automatically produces parts lists and
	drawings, and integrates the project with the company's
	schedule.&nbsp; Emails are sent automatically to all
	necessary stakeholders  with a projected
	timetable for the project and all relevant information.</p>
<p>The company will maintain a warehouse of building
	materials and components, with an up-to-date inventory
	stored in the company database.&nbsp; Our software
	will combine information from auto-generated parts
	lists with
	information from the warehouse inventory to produce
	purchase orders which are automatically emailed
	to suppliers such as Lysaght.&nbsp; In
	this way we will always have sufficient quantities
	of materials to build homes on schedule.&nbsp; There
	is no risk of a human forgetting to place an order,
	or making errors in calculating costs or quantities.</p>
<p>Our software will produce all the necessary drawings
	such as site plans and layouts for flooring, wall
	frames, roofing,
	cladding, electrical and plumbing.&nbsp; The drawings
	are automatically emailed to all the necessary
	contractors along with any other relevant information.
&nbsp;	Our software
development team will liaise closely with our preferred
	contractors to determine the optimal format
	for drawings and other information.</p>
<p>Fabrication drawings will also be generated automatically
	and sent to the workshop.&nbsp; In the first stage
	of the business these will be used by fabricators
	to assemble wall panels, trusses and other pre-fabricated
	components.&nbsp; Within 5 years this will all be
	done by robots.</p>
<p>As each component of the project is completed, this
	triggers the project management system built into
	our software to send emails to all necessary
	people and  update schedules.&nbsp; Our customers
	will be automatically notified as each stage of
	their home is completed, which will relieve stress,
	increase excitement, and improve our relationship
	with the customer.</p>
<p>Our software will be integrated with Quickbooks,
	copying all online sales and auto-generated purchase
	orders into our accounting system. </p>
<p>&nbsp;</p>
<hr>
<p>&nbsp;</p>
<p>Proceed to <a href="BuildingDesign.php">Building
Design</a>.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<?
include("../tpl/templateBottom.php");
?>